//Actions
export const TOGGLE_PHASE = "TOGGLE_PHASE"
export const SET_TRADE_PHASE_ACTIVE_PLAYER = "SET_TRADE_PHASE_ACTIVE_PLAYER"
export const SET_DISCOVER_PHASE_ACTIVE_PLAYER = "SET_DISCOVER_PHASE_ACTIVE_PLAYER"
export const SET_PHASE = "SET_PHASE"  //create for testing purposes
export const INCREMENT_ACTIVE_CARDS_PLAYED = "INCREMENT_ACTIVE_CARDS_PLAYED"
export const SET_CARDS_PLAYED_IN_TRADE_PHASE = "SET_CARDS_PLAYED_IN_TRADE_PHASE"

//Consts
export const PHASES = {
  DISCOVER: 'DISCOVER',
  TRADE: 'TRADE'
}
