export const ADD_COINS_TO_PLAYER = 'ADD_COINS_TO_PLAYER'
export const REMOVE_COINS_FROM_PLAYER = 'REMOVE_COINS_FROM_PLAYER'
export const ADD_CARD_TO_PLAYER = 'ADD_CARD_TO_PLAYER'
export const REMOVE_CARD_FROM_PLAYER = 'REMOVE_CARD_FROM_PLAYER'
